env:
  es6: true
  node: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - prettier
extends:
  - eslint:recommended
  - airbnb
  - prettier
parserOptions:
  ecmaVersion: 2019
  sourceType: module
  ecmaFeatures:
    impliedStrict: true
rules:
  indent: off
  prettier/prettier: error
