env:
  es6: true
  node: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
extends: "eslint:all"
parserOptions:
  ecmaVersion: 2019
  sourceType: module
  ecmaFeatures:
    impliedStrict: true
rules:
  eol-last: off
  func-names: off
  func-style:
    - error
    - declaration
  indent:
    - error
    - tab
  keyword-spacing: off
  line-comment-position: off
  lines-around-comment: off
  max-len: off
  max-lines: off
  max-lines-per-function: off
  multiline-ternary: off
  no-inline-comments: off
  no-magic-numbers: 
    - error
    - ignore:
      - 0
      - 1
      - -1
  no-tabs: off
  no-ternary: off
  no-var: off
  one-line: off
  padded-blocks: off
  prefer-arrow-callback: off
  prefer-const: off
  space-before-blocks: off
  space-before-function-paren: off