env:
  es6: true
  node: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - prettier
extends:
  - eslint:recommended
  - airbnb
  - prettier
parserOptions:
  ecmaVersion: 2019
  sourceType: module
  ecmaFeatures:
    impliedStrict: true
rules:
  prettier/prettier: error

  # Enforce consistent indentation.
  # Managed by prettier.
  indent: off

  # Disallow Array constructors.
  # Let programmer decide.
  no-array-constructor: off

  # Disallow Object constructors.
  # Let programmer decide.
  no-new-object: off

  # Disallow the unary operators ++ and --.
  # Always.
  no-plusplus: off

  # Suggest using const.
  # Managed by ESLint.
  prefer-const: off

  # Import Sorting.
  # Sort everything.
  sort-imports: 2

  # Require object keys to be sorted.
  # Sort everything.
  sort-keys: 2

  # Variable Sorting.
  # Sort everything
  sort-vars: 2
