language: node_js
node_js:
  - "10"
after_script:
  - |
    # Install and run Istanbul into Coveralls
    npm install -g istanbul@1.1.0-alpha.1 coveralls
    istanbul cover ./src/system.js && cat ./coverage/lcov.info | coveralls